name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
        check-latest: true

    - name: Test
      run: go test -v -ldflags="-checklinkname=0" ./...

    - name: Vet
      run: go vet ./... 